server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hz_demo?reWriteBatchedInserts=true
    username: postgres
    password: zahid7292

  hazelcast:
    config: classpath:hazelcast-server.xml
#    config: classpath:hazelcast-client.xml


  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        hbm2ddl:
          auto: update
