server:
  port: 8082
spring:
  datasource:
#    hikari:
#      poolName: SpringBootJPAHikariCP
#      maximumPoolSize: 100
#      minimumIdle: 10
#      idleTimeout: 30000
#      maxLifetime: 600000
#      connectionTimeout: 60000
#      leakDetectionThreshold: 0
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hz_demo?reWriteBatchedInserts=true
    username: postgres
    password: zahid7292
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        hbm2ddl:
          auto: update
#        cache:
#          use_second_level_cache: true
#          use_query_cache: false
#          auto_evict_collection_cache: false
#          use_structured_entries: false
#          region:
#            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory

#        jdbc:
#          lob:
#            non_contextual_creation: true
#          batch_size: 20
#          order_inserts: true
#          order_updates: true
